# Overrides for the CLI app

main-jar=peakaboo-cli.jar
main-class=org.peakaboo.cli.PeakabooCLI
description=Peakaboo XRF command line interface

# Flag this as CLI for windows
win-console=true

# Don't build a .desktop file for this one
linux-shortcut=false