name: Custom Build

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Datestamped Artifact
      run: mv ./Peakaboo-*.jar ./Peakaboo-SNAPSHOT-$(TZ=America/Toronto date +%Y%m%d)-${GITHUB_SHA::7}.jar
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Peakaboo Nightly
        path: ./Peakaboo-SNAPSHOT-*.jar
        retention-days: 14